### ISSUE TITLE
Analytics for Dash

### ISSUE THREAD

**Issue by AnaBanana91** [bdecentgmbh/moodle-block_dash#98]
Hi there,
we are using Dash Pro for our Moodle LMS to allow guests without registration to access some of our courses. The idea behind this is to have some easily accessible courses. 

To track guest traffic and know if the courses are used and by how many guests we added the plugin "Heatmap" which we use for our registrated users. Unfortunately, Heatmap is not able to track how many guests are accessing the open courses as they don't have a registered profile on the LMS. 

Do you know of any possibility to track data (not only views, but single users) in courses that are open to guest with Dash pro or another plugin?

Thanks in advance
Anna

**Comment by stefanscholz** [comment]
Hi @AnaBanana91 ,

thanks for reaching out! Here's how "guest" access in Moodle works: if guest login is enabled, then "visitors" of your page are logged in as the user with the ID 1, the "guest user". For this reason, the only way to track them would be to differentiate maybe by ip address or something else, i.e. using website analytics.

I have an idea though — it's not exactly the solution that you look for, but we might be close enough that a little development could get us there.

Our plugin "Magic" (an authentication plugin) tries to make access to Moodle as simple and convenient as possible. This is achieved via a number of features:

- Login without password (with magic links)
- Registration with just an email address (no other data)
- Campaigns (see below)

A campaign is essentially a highly customizable registration form where you can choose which form fields are required (e.g. only email) and then upon successful sign up (among many other things), we can add users to cohorts, enrol them into a course, group them, send notifications, assign them to other users etc.

I've created a simple example here:
https://bdecent.io/auth/magic/campaigns/view.php?code=SEdQYUhv

This campaign will create a new user with the provided email address and then redirect the user directly to the course. Access to the course is possible immediately (and of course also to other courses, since we now have a user). 
An email will be send to the email address to confirm the account.

As noted above, with a little bit of development, we could streamline this process even further, e.g. by creating a user account automatically if a visitor tries to access a course.

If this sounds interesting for you, let me know, and we explore this further.

Hope this helps!
Stefan

**Comment by AnaBanana91** [comment]
Thanks, Stefan. Will discuss that with the team and get back to you :-)
